apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: team-x
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      imagePullSecrets:
        - name: hub.softleader.com.tw
      containers:
      - name: team-x
        image: "hub.softleader.com.tw/team-x:0.0.16-nanshan"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          httpGet:
            path: /info
            port: 8080
          initialDelaySeconds: 60
        resources:
          requests:
            cpu: 0
            memory: 256Mi
          limits:
            cpu: 2
            memory: 1024Mi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker,efk"
        - name: EUREKA_SERVICE
          value: $(EUREKA_SERVICE)
        - name: EUREKA_INGRESS_PATH
          value: $(EUREKA_INGRESS_PATH)
        - name: INTEGRATION_SERVICE
          value: $(INTEGRATION_SERVICE)
        - name: INTEGRATION_INGRESS_PATH
          value: $(INTEGRATION_INGRESS_PATH)
        - name: HELLO_SERVICE
          value: $(HELLO_SERVICE)
        - name: HELLO_INGRESS_PATH
          value: $(HELLO_INGRESS_PATH)
        - name: TEAM_X_SERVICE
          value: $(TEAM_X_SERVICE)
        - name: TEAM_X_INGRESS_PATH
          value: $(TEAM_X_INGRESS_PATH)
