commonLabels:
  app: hello
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
vars:
  - name: HELLO_INGRESS_PATH
    objref:
      kind: Ingress
      name: hello
      apiVersion: extensions/v1beta1
    fieldref:
      fieldpath: spec.rules[0].http.paths[0].path
  - name: HELLO_SERVICE
    objref:
      kind: Service
      name: hello
      apiVersion: v1