apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: hub.softleader.com.tw
      containers:
      - name: redis
        image: "hub.softleader.com.tw/redis:alpine"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 0
            memory: 1024Mi
          limits:
            cpu: 1
            memory: 2048Mi
        volumeMounts:
          - mountPath: /data
            name: "redis-data"
      volumes:
      - name: "redis-data"
        persistentVolumeClaim:
          claimName: "redis-pvc"