apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  "redis-pvc"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "redis"
  resources:
    requests:
      storage: 1T
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "redis-pv"
spec:
  storageClassName: "redis"
  capacity:
    storage: 1T
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /pv/redis